---
- name: create directory 
  file:
    path: /home/backup/mysql
    owner: backup
    group: backup
    state: directory
    mode: 0755

- name: Replace mysql conf file
  template:
    src: my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: 0400
  notify: restart mysql

- name: MySQL user 
  community.mysql.mysql_user:
    name: backup
    password: "{{ backup_pass }}"
    priv: 
      '*.*': 'LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Make a cronjob
  template:
    src: mysql-backup
    dest: /etc/cron.d/mysql-backup
    mode: 0755
