- name: Installing Nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
    
- name: Replace the default Nginx conf file
  ansible.builtin.copy:
    src: ../files/default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes