- name: Installing Nginx package
  ansible.builtin.apt:
    name: nginx
    state: latest
    
- name: Replace the default Nginx conf file
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
