- name: Installing Nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
    
- name: Replace the default Nginx conf file
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
