- name: Download binary file
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_386
    dest: /opt/influxdb_exporter
    mode: '755'

- name: Create influxdb_exporter service
  template:
    src: influx_exporter.service.j2
    dest: /etc/systemd/system/influxdb_exporter.service
  notify:
    - restart influxdb_exporter
    - daemon-reload

- name: Copy influxdb_exporter.sh
  copy:
    src: influxdb_exporter.sh
    dest: /usr/local/bin/influxdb_exporter
    owner: ubuntu
    mode: 0777
  notify: restart influxdb_exporter

- name: Start influxdb_exporter
  service:
    name: influxdb_exporter
    state: started
    enabled: true
