---
- name: Install haproxy & keepalived
  apt:  
    name: haproxy

- name: Replace haproxy cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Turn on both services
  service: 
    name: haproxy
    state: started
    enabled: yes

