---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add this repo for stable release
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu focal stable"
    state: present
    
- name: Install influxdb and telegraf
  apt:
    name: 
    - influxdb
    - telegraf

- name: Configure influxdb
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: restart influx

- name: Configure telegraf
  copy: 
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: telegraf restart

- name: Verify apps are running
  service:
    name: "{{ item }}"
    state: started 
    enabled: true 
  loop:
    - influxdb
    - telegraf
