---
- name: Grafana APT repo key
  apt_key:
    url: https://packages.grafana.com/gpg.key 
    state: present

- name: Grafana APT repo
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    
- name: Install grafana
  apt:
    name: grafana

- name: Grafana config template
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana

- name: Grafana provisioning
  template:
    src: grafana_provision.yaml.j2
    dest: /etc/grafana/provisioning/datasources/default.yaml
  notify: restart grafana

- name: Grafana dashboard directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana

- name: Add grafana dashboard
  copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/
  notify: restart grafana

- name: Verify grafana is running
  service:
    name: grafana-server
    state: started
    enabled: true 
