---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.grafana.com/gpg.key 
    state: present

- name: add this repo for stable release
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    
- name: Install grafana
  apt:
    name: grafana
  notify: restart grafana

- name: change config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - restart grafana

- name: Verify grafana is running
  service:
    name: grafana-server
    state: started
    enabled: true 
