---
- name: Create all Grafana directories
  ansible.builtin.file:
    name: "{{ item }}"
    recurse: yes
    state: directory
  loop:
    - /opt/grafana
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Grafana config
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: yes

- name: Grafana datasources
  ansible.builtin.template:
    src: "{{ item }}.yaml"
    dest: "/opt/grafana/provisioning/datasources/{{ item }}"
  loop:
    - sample
    - latency
    - telegraf

- name: Grafana dashboard
  ansible.builtin.template:
    src: main.yaml
    dest: /opt/grafana/provisioning/dashboards/main.yaml

- name: Grafana dashboard panels
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item  }}"
  loop:
    - main.json
    - MySQL.json
    - syslog.json

- name: Grafana Docker container
  docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    container_default_behavior: no_defaults 
    restart_policy: always
