
- name: Grafana directory
  file:
    path: /opt/grafana
    state: directory

- name: Grafana config
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: yes

# - name: Grafana provisioning
#   ansible.builtin.template:
#     src: "{{ item }}.yaml.j2"
#     dest: "/opt/grafana/provisioning/{{ item }}/default.yaml"
#   loop:
#     - dashboards
#     - datasources
#   notify: restart grafana

- name: Grafana Docker container
  docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    container_default_behavior: no_defaults 
    restart_policy: always
