- name: Install uwsgi packages
  apt:
    name:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql

- name: Copy ini file
  ansible.builtin.template:
    src: ../templates/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0644
  notify: restart uwsgi

- name: Start service uWSGI if not started
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
    
# - name: Restart after config change
#   ansible.builtin.template:
#     src: ./agama.ini
#     dest: /etc/uwsgi/apps-enabled/
#   notify:
#   -  Restart uwsgi

#   handlers:
#     - name: Restart uwsgi
#       ansible.builtin.service:
#         name: uwsgi
#         state: restarted


# - name: Install Flask python package
#   pip:
#     name: Flask-SQLAlchemy

# - name: Download the app
#   get_url:
#     url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
#     dest: /opt/agama
    
# - name: Start service uWSGI , if not started
#   ansible.builtin.service:
#     name: uWSGI 
#     state: started
