---
- name: Setup
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - setup:

- name: DNS servers
  hosts: db_servers
  become: yes
  roles: 
    - bind

- name: Configure DNS
  hosts: all
  become: yes
  roles: 
    - bind