- name: Installing pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Flask python package
  pip:
    name: Flask-SQLAlchemy

- name: Download the app
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
    
- name: Copy ini file
  ansible.builtin.copy:
    src: ./agama.ini
    dest: /etc/uwsgi/apps-enabled/
    owner: agama