- name: Installing dependencies
  ansible.builtin.apt:
    name: python3-flask-sqlalchemy
    state: present

- name: Download the app
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/


