- name: Linux user agama
  ansible.builtin.user:
    name: agama
    
- name: Dir for agama
  file:
    path: /opt/agama
    state: directory 

- name: Download the app
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build Agama image
  docker_image:
    name: agama
    build:
      path: /opt/agama
      network: host
    source: build   

- name: Agama container
  docker_container:
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{agama_port + 1}}:8000"
    container_default_behavior: no_defaults 
    restart_policy: always

- name: Agama container 2
  docker_container:
    name: agama2
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{agama_port + 2}}:8000"
    container_default_behavior: no_defaults 
    restart_policy: always
