- name: Add the user "backup" and generate keys
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: ansible create directory 
  file:
    owner: backup
    path: /home/backup/restore
    state: directory

- name: Install duplicity
  apt:
    name: duplicity
    state: present

- name: Touch a ssh known hosts file
  template:
    src: known_hosts.j2
    owner: backup
    dest: /home/backup/.ssh/known_hosts
