- name: Install mysqld exporter
  apt:
    name: prometheus-mysqld-exporter

- name: MySQL user 
  community.mysql.mysql_user:
    name: exporter
    password: "{{ mysql_exporter }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create config
  template:
    src: my.cnf.j2
    dest: /home/ubuntu/.my.cnf
  notify:
    - restart mysqld_exporter

- name: Sleep for 6 seconds 
  pause:
    seconds: 6

- name: Verify exporter is running
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true 
