- name: MySQL user 
  community.mysql.mysql_user:
    name: exporter
    password: "{{ mysql_exporter }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: 0600
  notify: restart mysqld_exporter

- name: Install mysqld exporter
  apt:
    name: prometheus-mysqld-exporter

- name: Verify exporter is running
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true 

- name: Change slave config 
  ansible.builtin.copy:
    src: ../files/prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
    # owner: 
    # mode: 0777
  notify: restart mysqld_exporter

