- name: Install MYSQL-server
  ansible.builtin.apt:
    pkg: 
    - mysql-server
    - python3-pymysql

- name: Replace the default mysql conf file
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user for Agama
  community.mysql.mysql_user:
    state: present
    name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user for replication
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ replication_pass }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Read only ON
  community.mysql.mysql_variables:
    variable: read_only
    value: 'ON'
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: inventory_hostname != mysql_host
  notify: 
    - Reset MYSQL source
    - Reset MYSQL replica
  tags: ch

- name: Read only OFF
  community.mysql.mysql_variables:
    variable: read_only
    value: 'OFF'
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock 
  when: inventory_hostname == mysql_host
