- name: Install MYSQL-server
  ansible.builtin.apt:
    pkg: 
    - mysql-server
    - python3-pymysql

- name: Replace the default mysql conf file
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql

- name: start & enable - mysql
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user 
  community.mysql.mysql_user:
    state: present
    name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock