---
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://{{ prometheus_host }}:9090/prometheus
    password:
    user:
    database:
    isDefault: True
    version: 1
    editable: false
