---
apiVersion: 1

datasources:
  - name: telegraf
    type: influxdb
    access: proxy
    orgId: 1
    url: http://vm2:8086
    password:
    user:
    database: telegraf
    isDefault: false
    version: 1
    editable: false
