---

- name: Install fping
  apt:
    name: fping 
    state: latest

- name: Add the user "pinger" and generate keys
  user:
    name: pinger
    home: /etc/pinger
    shell: /bin/bash

- name: Copy pinger conf
  template: 
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
    owner: pinger
  notify: daemon-reload

- name: Copy the pinger.sh
  copy:
    src: ../files/pinger.sh
    dest: /usr/local/bin/pinger
    owner: pinger
    mode: 0777
  notify: restart pinger

- name: Create a pinger.service
  template: 
    src: pinger.service.j2
    dest: /etc/systemd/system/pinger.service
  notify: 
    - restart pinger
    - daemon-reload

- name: Start & enable the pinger if not started
  service: 
    name: pinger
    state: started
    enabled: true
    