---
- name: Install nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Sleep for 12 seconds 
  pause:
    seconds: 12

- name: Verify exporter is running
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true 