---
- name: Install nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Verify exporter is running
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true 