---
- name: Docker package
  apt:  
    name:
    - docker.io
    - python3-docker
    - iptables-persistent

- name: IPtables template
  template:
    src: iptables
    dest: /etc/iptables/rules.v4

- name: Iptables restore
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    state: restored
    table: mangle

- name: Docker service
  service:
    name: docker
    state: started
    enabled: yes
