---
- name: Install bind9
  apt:
    name:
    - bind9
    - python3-dnspython
  
- name: Installing the options
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: true
  notify: restart bind
  
- name: Installing the db.domain
  when: inventory_hostname in groups['dns_master']
  template: 
    src: db.domain.j2
    dest: /var/cache/bind/db.{{ fqdn }}
    force: no
  notify: reload rndc

- name: Installing the db.reverse
  when: inventory_hostname in groups['dns_master']
  template: 
    src: db.domain.reverse
    dest: /var/cache/bind/db.{{ reverse_fqdn }}
    force: no
  notify: reload rndc

- name: Installing the local
  template: 
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind

- name: Verify bind9 is running
  service:
    name: bind9
    state: started 
    enabled: true 
