---
- name: Install bind9
  apt:
    pkg: bind9
  #  update_cache: yes
  
- name: Installing the options
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind

- name: Installing the db
  template: 
    src: db.{{ domain }}.j2
    dest: /var/cache/bind/db.{{ domain }}
  notify: restart bind


- name: Installing the local
  template: 
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind

- name: debug
  debug:
    msg: "
    {% for vm in groups['all'] %} 
    nameserver {{ hostvars[vm]['ansible_default_ipv4']['address'] }}
    {% endfor %}"
    # "msg": " nameserver 192.168.42.93 nameserver 192.168.42.87"
