---
- name: Install bind9
  apt:
    pkg: bind9
    # update_cache: yes
  
- name: Installing the options
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind
  
- name: Installing the local
  template: 
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind

- name: Installing the db
  template: 
    src: db.{{ domain }}.j2
    dest: /var/cache/bind/db.{{ domain }}
  notify: reload rndc
