- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: hostname
  hostname: 
    name: "{{inventory_hostname}}"
    use: debian

- name: Debugging only
  debug:
    # msg: "{{ hostvars['vm1']['ansible_default_ipv4']['address'] }}"
