---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add this repo for stable release
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu focal stable"
    state: present
    
- name: Install telegraf
  apt:
    name: 
    - telegraf

- name: Configure telegraf
  template: 
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: telegraf restart

- name: Verify telegraf is running
  service:
    name: telegraf
    state: started 
    enabled: true 
